#dockerfile에서 copy를 쓰지않고 bind mount를 이용해서 원하는 결과를 얻음
version: "3"
services:
  web_scrapper:
    container_name: naver_movie
    build: .
    working_dir: /usr/src
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - type: bind
        source: ./utils
        target: /usr/src/utils
      - type: bind
        source: ./main.py
        target: /usr/src/main.py
      - ./data:/usr/src/data
    command: bash -c
      "cd /usr/src
      && python /usr/src/main.py"