#dockerfile에서 copy를 쓰지않고 bind mount를 이용해서 원하는 결과를 얻음
version: "3"
services:
  ex2:
    container_name: naver_movie
    image: naver_movie_scrapper
    working_dir: /usr/src
    volumes:
      - type: bind
        source: ./utils
        target: /usr/src/utils
      - type: bind
        source: ./main.py
        target: /usr/src/main.py
      - ./data:/usr/src/data
    command: bash -c
      "cd /usr/src
      && python /usr/src/main.py"
    














# dockerfile에서 copy를 써야만 원하는 결과가 나오는것
# ''' 
# version: "3"
# services:
#   ex2:
#     container_name: ex2
#     build: .
#     # restart: always
#     working_dir: /usr/src
#     command: bash -c
#       "cd /usr/src
#       && python /usr/src/test.py"
#     volumes:
#       - ./test_data:/usr/src/data
# '''
